### ISSUE TITLE
Players Cannot Walk Through 2+ High Safe Area Blocks Going South

### ISSUE THREAD

**Issue by Earbuds** [bfox1/SAO#14]
Just something I noticed while playing around with the blocks.

Players cannot walk through Safe Area blocks going south if the blocks are stacked 2 or higher.

Example [here](https://www.youtube.com/watch?v=gqTX6io8znY&feature=youtu.be).

**Comment by m-sterling** [comment]
Someone should fix this by the first beta. Not game-breaking priority. I'll look into it, but no promises that it'll be fixed. :confounded:

**Comment by bfox1** [comment]
This is Now fixed. Not only can you walk through it just fine, but it is now transparent.
